version: "3.9"
services:
#  tell-me-jira:
#    build: .
#    env_file:
#      - .env
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/create_tables.sql